[package]
name = "olive"
version = "0.1.0"
edition = "2024"

[dependencies]
glfw = "0.52.0"
gl = "0.14.0"
iced = { version = "0.12.1", features = ["wgpu", "tokio"] }
rodio = "0.17"
tokio = { version = "1", features = ["full"]}
